function fig = sinead_preprocess()
% ___________________________________________________________________________
% SINEAD (Software Integrating NEuroimaging And other Data)
%
% Copyright 2016 ISRC-Ulster
% Reference 
% Youssofzadeh et al, Multi-kernel learning with Dartel enhances
% combined MRI-PET classification and prediction
% of Alzheimer’s disease: group and individual
% data analyses, submitted to Human Brain Mapping 
% 
% 
% v1.0 Vahab Youssofzadeh 05/06/2016
% ___________________________________________________________________________
disp('cadsum_preprocessing ...')
col = [0.8020 0.9072 0.4014];
F = 10; % fontsize

h0 = figure('Color',[1 1 1], ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[450 250 390 210], ...
	'Tag','Main', ...
	'NumberTitle','off',...
	'Name','ToolBox : SINEAD v.1', ...
    'MenuBar','none', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
    'Fontsize', F, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 85 166 16], ...
	'String','Set origin to centre', ...
	'CallBack','sinead_preprocess_setorg');
h2 = uicontrol('Parent',h0, ...
    'Fontsize', F, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 60 166 16], ...
	'String','MRI/PET preprocessing', ...
	'CallBack','sinead_preprocess_mripet');
h3 = uicontrol('Parent',h0, ...
    'Fontsize', F, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 35 166 16], ...
	'String','Tissue volumes', ...
	'CallBack','sinead_tissuevolumes');
h4 = uicontrol('Parent',h0, ...
    'Fontsize', F, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 10 166 16], ...
	'String','Close', ...
	'CallBack','delete(gcf)');
% 	'CallBack','delete(gcf), spm(''Clear'')');
h5 = uicontrol('Parent',h0, ...
    'Fontsize', F, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[16 110 280 36], ...
	'String','Preprocessing (SPM12)', ...
	'Style','text', ...
	'Tag','StaticText5');
h6 = uicontrol('Parent',h0, ...
    'Fontsize', F, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[1 85 66 16], ...
	'String','Display image', ...
	'CallBack','sinead_preprocess_disp');
h7 = uicontrol('Parent',h0, ...
    'Fontsize', F, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[1 60 66 16], ...
	'String','Check Reg', ...
	'CallBack','sinead_preprocess_checkReg');
if nargout > 0, fig = h0; end
