function fig = sinead_CorThickness()
% ___________________________________________________________________________
% sinead (Classification of AD Sufferers using Machine Learning)
%
% Copyright 2016 ISRC-Ulster
% Reference 
% Youssofzadeh et al, Multi-kernel learning with Dartel enhances
% combined MRI-PET classification and prediction
% of Alzheimer’s disease: group and individual
% data analyses, submitted to Human Brain Mapping 
% 
% 
% v1.0 Vahab Youssofzadeh 05/06/2016
% ___________________________________________________________________________
disp('Cortical thickness analysis ...')
col = [0.4020 0.4072 0.5014];

h0 = figure('Color',[1 1 1], ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[1250 250 390 210], ...
	'Tag','Main', ...
	'NumberTitle','off',...
	'Name','ToolBox : SINEAD v.1', ...
    'MenuBar','none', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 85 166 16], ...
	'String','Thickness view', ...
	'CallBack','sinead_CorThickness_ThicknessView','ForegroundColor',[1,1,1]);
h2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 60 166 16], ...
	'String','Thickness stats', ...
	'CallBack','sinead_CorThickness_ThicknessStat','ForegroundColor',[1,1,1]);
h3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 35 166 16], ...
	'String','-', ...
	'CallBack','sinead_CorTickness_TicknessStat','ForegroundColor',[1,1,1]);
h4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 10 166 16], ...
	'String','Close', ...
	'CallBack','delete(gcf)','ForegroundColor',[1,1,1]);
h5 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[16 110 280 36], ...
	'String','Cortical thickness (surfstat)', ...
	'Style','text', ...
	'Tag','StaticText5','ForegroundColor',[0,0,0]);
if nargout > 0, fig = h0; end
